# Generated by Django 4.2.6 on 2023-11-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
