# Generated by Django 4.2.6 on 2023-11-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manage', '0003_task_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='on_time_completion',
            field=models.BooleanField(default=False),
        ),
    ]
