# Generated by Django 4.2.6 on 2023-11-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_target_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_tasks_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
