# Generated by Django 4.2.6 on 2023-11-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_category_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_tasks_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
