# Generated by Django 4.2.6 on 2023-11-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_target_userprofile_targetpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='target',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
